# Airbnb Dataset Exploration

## Objective

The goal of this notebook is to understand the Airbnb listings dataset before building the data pipeline.

This includes:

- Understanding the dataset structure
- Identifying important columns
- Detecting missing values
- Understanding data types
- Identifying potential data quality issues

In [2]:
import os

os.chdir(r"D:\Projects\expernetic-airbnb-assessment")
print(os.getcwd())

D:\Projects\expernetic-airbnb-assessment

In [5]:
import pandas as pd 
df = pd.read_csv("data/raw/listings.csv.gz")

In [10]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,11551,https://www.airbnb.com/rooms/11551,20260619061251,2026-06-25,city scrape,Artistic London Pied-à-Terre,Live like a local in this quintessential Londo...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,43039,...,4.84,4.54,4.49,NaN,NaN,1,1,0,0,0.99
1,13913,https://www.airbnb.com/rooms/13913,20260619061251,2026-06-25,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.88,4.79,4.79,NaN,NaN,2,1,1,0,0.30
2,15400,https://www.airbnb.com/rooms/15400,20260619061251,2026-06-26,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,NaN,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.84,4.94,4.74,NaN,NaN,1,1,0,0,0.49
3,17402,https://www.airbnb.com/rooms/17402,20260619061251,2026-06-29,city scrape,Spacious Fitzrovia 3bed/2bath By Soho & Oxford St,"Stay in this spacious 3-bedroom, 2-bath apartm...",NaN,https://a0.muscache.com/pictures/39d5309d-fba7...,67564,...,4.73,4.89,4.62,NaN,NaN,2,2,0,0,0.31
4,513198,https://www.airbnb.com/rooms/513198,20260619061251,2026-06-29,city scrape,Stunning views over Central London! (room),Wake up to the sound of Big Ben!<br /><br />Th...,NaN,https://a0.muscache.com/pictures/6442310/e4b3e...,2528030,...,4.74,4.72,4.42,NaN,NaN,2,1,1,0,0.25

In [16]:
df.shape

(92638, 90)

In [17]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_profile_id', 'host_profile_url', 'host_name',
       'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 92638 entries, 0 to 92637
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            92638 non-null  int64
 1   listing_url                                   92638 non-null  str
 2   scrape_id                                     92638 non-null  int64
 3   last_scraped                                  92638 non-null  str
 4   source                                        92638 non-null  str
 5   name                                          92638 non-null  str
 6   description                                   90549 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   92633 non-null  str
 9   host_id                                       92638 non-null  int64
 10  host_url                                      92638 non-null  str
 11  host_profile_id                               92562 non-null  float64
 12  host_profile_url                              92554 non-null  str
 13  host_name                                     92562 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      92562 non-null  float64
 16  hosts_time_as_user_months                     92562 non-null  float64
 17  hosts_time_as_host_years                      92561 non-null  float64
 18  hosts_time_as_host_months                     92561 non-null  float64
 19  host_location                                 69928 non-null  str
 20  host_about                                    49229 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             92562 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              92562 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           92562 non-null  float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          92562 non-null  str
 32  host_identity_verified                        92562 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        92638 non-null  str
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      92638 non-null  float64
 37  longitude                                     92638 non-null  float64
 38  property_type                                 92638 non-null  str
 39  room_type                                     92638 non-null  str
 40  accommodates                                  92638 non-null  int64
 41  bathrooms                                     57762 non-null  float64
 42  bathrooms_text                                92504 non-null  str
 43  bedrooms                                      68655 non-null  float64
 44  beds                                          60163 non-null  float64
 45  amenities                                     92638 non-null  str
 46  price                                         62240 non-null  str
 47  price_quote_checkin_date                      64771 non-null  str
 48  price_quote_checkout_date                     64771 non-null  str
 49  price_quote_total_price                       62240 non-null  float64
 50  price_quote_price_per_night                   62240 non-null  float64
 51  price_quote_raw                               64771 non-null  str
 52  minimum_nights                                92633 non-null  float64
 53  maximum_nights                                92633 non-null  float64
 54  minimum_minimum_nights                        92633 non-null  float64
 55  maximum_minimum_nights                        92633 non-null  float64
 56  minimum_maximum_nights                        92633 non-null  float64
 57  maximum_maximum_nights                        92633 non-null  float64
 58  minimum_nights_avg_ntm                        92638 non-null  float64
 59  maximum_nights_avg_ntm                        92638 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              91778 non-null  str
 62  availability_30                               92638 non-null  int64
 63  availability_60                               92638 non-null  int64
 64  availability_90                               92638 non-null  int64
 65  availability_365                              92638 non-null  int64
 66  calendar_last_scraped                         92638 non-null  str
 67  number_of_reviews                             92638 non-null  int64
 68  number_of_reviews_ltm                         92638 non-null  int64
 69  number_of_reviews_l30d                        92638 non-null  int64
 70  availability_eoy                              92638 non-null  int64
 71  number_of_reviews_ly                          92638 non-null  int64
 72  estimated_occupancy_l365d                     92638 non-null  int64
 73  estimated_revenue_l365d                       62240 non-null  float64
 74  first_review                                  70711 non-null  str
 75  last_review                                   70711 non-null  str
 76  review_scores_rating                          70711 non-null  float64
 77  review_scores_accuracy                        70697 non-null  float64
 78  review_scores_cleanliness                     70702 non-null  float64
 79  review_scores_checkin                         70673 non-null  float64
 80  review_scores_communication                   70692 non-null  float64
 81  review_scores_location                        70672 non-null  float64
 82  review_scores_value                           70672 non-null  float64
 83  license                                       0 non-null      float64
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                92638 non-null  int64
 86  calculated_host_listings_count_entire_homes   92638 non-null  int64
 87  calculated_host_listings_count_private_rooms  92638 non-null  int64
 88  calculated_host_listings_count_shared_rooms   92638 non-null  int64
 89  reviews_per_month                             70711 non-null  float64
dtypes: float64(44), int64(18), str(28)
memory usage: 63.6 MB

In [15]:
df.isnull().sum()

id                                                  0
listing_url                                         0
scrape_id                                           0
last_scraped                                        0
source                                              0
                                                ...
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
reviews_per_month                               21927
Length: 90, dtype: int64

In [18]:
print(f"Rows : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows : 92638
Columns : 90

In [20]:
print(df)

                        id                                       listing_url  \
0                    11551                https://www.airbnb.com/rooms/11551
1                    13913                https://www.airbnb.com/rooms/13913
2                    15400                https://www.airbnb.com/rooms/15400
3                    17402                https://www.airbnb.com/rooms/17402
4                   513198               https://www.airbnb.com/rooms/513198
...                    ...                                               ...
92633  1710890123987639456  https://www.airbnb.com/rooms/1710890123987639456
92634  1710905101305350643  https://www.airbnb.com/rooms/1710905101305350643
92635  1710906779963511330  https://www.airbnb.com/rooms/1710906779963511330
92636  1710920060139021009  https://www.airbnb.com/rooms/1710920060139021009
92637  1710933572119600327  https://www.airbnb.com/rooms/1710933572119600327

            scrape_id last_scraped       source  \
0      20260619061251   2026-06-25  city scrape
1      20260619061251   2026-06-25  city scrape
2      20260619061251   2026-06-26  city scrape
3      20260619061251   2026-06-29  city scrape
4      20260619061251   2026-06-29  city scrape
...               ...          ...          ...
92633  20260619061251   2026-06-29  city scrape
92634  20260619061251   2026-06-29  city scrape
92635  20260619061251   2026-06-29  city scrape
92636  20260619061251   2026-06-29  city scrape
92637  20260619061251   2026-06-29  city scrape

                                                    name  \
0                           Artistic London Pied-à-Terre
1                    Holiday London DB Room Let-on going
2                    Bright Chelsea  Apartment. Chelsea!
3      Spacious Fitzrovia 3bed/2bath By Soho & Oxford St
4             Stunning views over Central London! (room)
...                                                  ...
92633             Spacious 4 bed 2 bathroom with Air con
92634           beautiful location Hyde Park just around
92635               Elegant 4BR Apartment Near Hyde Park
92636  Cozy Urban Studio Escape | Perfect Central London
92637                           Single - Shared bathroom

                                             description  \
0      Live like a local in this quintessential Londo...
1      My bright double bedroom with a large window h...
2      Lots of windows and light.  St Luke's Gardens ...
3      Stay in this spacious 3-bedroom, 2-bath apartm...
4      Wake up to the sound of Big Ben!<br /><br />Th...
...                                                  ...
92633  Keep it simple at this peaceful and centrally-...
92634  Enjoy a stylish experience at this centrally-l...
92635  Stay in the heart of Central London at this st...
92636  .Welcome to your comfortable studio stay in th...
92637  Nestled within a magnificent early 18th-centur...

       neighborhood_overview  \
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
...                      ...
92633                    NaN
92634                    NaN
92635                    NaN
92636                    NaN
92637                    NaN

                                             picture_url    host_id  ...  \
0      https://a0.muscache.com/pictures/prohost-api/H...      43039  ...
1      https://a0.muscache.com/pictures/miso/Hosting-...      54730  ...
2      https://a0.muscache.com/pictures/428392/462d26...      60302  ...
3      https://a0.muscache.com/pictures/39d5309d-fba7...      67564  ...
4      https://a0.muscache.com/pictures/6442310/e4b3e...    2528030  ...
...                                                  ...        ...  ...
92633  https://a0.muscache.com/pictures/miso/Hosting-...  654607609  ...
92634  https://a0.muscache.com/pictures/hosting/Hosti...  480497204  ...
92635  https://a0.muscache.com/pictures/hosting/Hosti...  156904677  ...
92636  https://a0.muscache.com/pictures/hosting/Hosti...  222720392  ...
92637  https://a0.muscache.com/pictures/hosting/Hosti...  131591665  ...

      review_scores_communication  review_scores_location review_scores_value  \
0                            4.84                    4.54                4.49
1                            4.88                    4.79                4.79
2                            4.84                    4.94                4.74
3                            4.73                    4.89                4.62
4                            4.74                    4.72                4.42
...                           ...                     ...                 ...
92633                         NaN                     NaN                 NaN
92634                         NaN                     NaN                 NaN
92635                         NaN                     NaN                 NaN
92636                         NaN                     NaN                 NaN
92637                         NaN                     NaN                 NaN

      license  instant_bookable  calculated_host_listings_count  \
0         NaN               NaN                               1
1         NaN               NaN                               2
2         NaN               NaN                               1
3         NaN               NaN                               2
4         NaN               NaN                               2
...       ...               ...                             ...
92633     NaN               NaN                               2
92634     NaN               NaN                               3
92635     NaN               NaN                              48
92636     NaN               NaN                              10
92637     NaN               NaN                              23

       calculated_host_listings_count_entire_homes  \
0                                                1
1                                                1
2                                                1
3                                                2
4                                                1
...                                            ...
92633                                            2
92634                                            3
92635                                           48
92636                                           10
92637                                           18

       calculated_host_listings_count_private_rooms  \
0                                                 0
1                                                 1
2                                                 0
3                                                 0
4                                                 1
...                                             ...
92633                                             0
92634                                             0
92635                                             0
92636                                             0
92637                                             5

       calculated_host_listings_count_shared_rooms reviews_per_month
0                                                0              0.99
1                                                0              0.30
2                                                0              0.49
3                                                0              0.31
4                                                0              0.25
...                                            ...               ...
92633                                            0               NaN
92634                                            0               NaN
92635                                            0               NaN
92636                                            0               NaN
92637                                            0               NaN

[92638 rows x 90 columns]

In [19]:
df.dtypes.value_counts()

float64    44
str        28
int64      18
Name: count, dtype: int64

In [30]:
missing = df.isnull().sum()

missing_percentage = (missing/len(df))*100

missing_df = pd.DataFrame({
    "Misssing Values":missing,
    "Percentage" : missing_percentage
})

missing_df.sort_values(
    by="Percentage",
    ascending=False
).head(20)

                              Misssing Values  Percentage
neighborhood_overview                   92638  100.000000
host_since                              92638  100.000000
host_response_time                      92638  100.000000
host_thumbnail_url                      92638  100.000000
host_acceptance_rate                    92638  100.000000
host_response_rate                      92638  100.000000
host_verifications                      92638  100.000000
neighbourhood                           92638  100.000000
host_total_listings_count               92638  100.000000
host_neighbourhood                      92638  100.000000
calendar_updated                        92638  100.000000
instant_bookable                        92638  100.000000
license                                 92638  100.000000
neighbourhood_group_cleansed            92638  100.000000
host_about                              43409   46.858740
bathrooms                               34876   37.647618
beds                                    32475   35.055809
price_quote_price_per_night             30398   32.813748
price                                   30398   32.813748
estimated_revenue_l365d                 30398   32.813748

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df["room_type"].value_counts()

room_type
Entire home/apt    61377
Private room       30878
Shared room          203
Hotel room           180
Name: count, dtype: int64

In [29]:
df["property_type"].value_counts().head(10)

property_type
Entire rental unit             40129
Private room in rental unit    12907
Private room in home           10846
Entire home                     9153
Entire condo                    7935
Private room in condo           3047
Entire serviced apartment       1862
Room in hotel                   1253
Private room in townhouse       1097
Entire townhouse                1009
Name: count, dtype: int64